#pragma once

// Crazy Taxi (XBLA) -- PPC image layout constants
#define PPC_IMAGE_BASE 0x82000000
#define PPC_CODE_BASE  0x820C0000
#define PPC_CODE_SIZE  0x00209000
#define PPC_IMAGE_SIZE 0x00BC0000

// Safe indirect call macro -- validates target address is within code range.
// Falls back to function table lookup for import thunks and out-of-range calls.
// Adapted from simpsonsarcade's ppc_detail.h with import thunk resolution.
#ifndef PPC_CALL_INDIRECT_FUNC
#define PPC_CALL_INDIRECT_FUNC(ctx, base, addr)                                \
    do {                                                                        \
        uint32_t _target = (addr);                                             \
        if (_target == 0) {                                                    \
            /* NULL call -- skip with warning */                               \
            static int _warn_count = 0;                                        \
            if (_warn_count++ < 10)                                            \
                printf("[WARN] NULL indirect call (LR=0x%08X)\n",              \
                       ctx.lr.u32);                                            \
            break;                                                             \
        }                                                                      \
        if (_target >= PPC_CODE_BASE &&                                        \
            _target < PPC_CODE_BASE + PPC_CODE_SIZE) {                         \
            /* In-range: look up in function table */                          \
            auto _fn = PPC_LOOKUP_FUNC(_target);                               \
            if (_fn) { _fn(ctx, base); break; }                                \
        }                                                                      \
        /* Try import thunk resolution:                                        \
           Import stubs are: lis r11,hi / lwz r12,lo(r11) / mtctr r12 / bctr  \
           We read the IAT pointer and resolve via the function table. */       \
        {                                                                      \
            uint32_t _off = _target - PPC_IMAGE_BASE;                          \
            if (_off + 16 <= PPC_IMAGE_SIZE) {                                 \
                uint32_t _i0 = __builtin_bswap32(                              \
                    *(uint32_t*)(base + _off));                                \
                uint32_t _i1 = __builtin_bswap32(                              \
                    *(uint32_t*)(base + _off + 4));                            \
                if ((_i0 >> 16) == 0x3D60 && (_i1 >> 16) == 0x818B) {         \
                    uint32_t _hi = (_i0 & 0xFFFF) << 16;                       \
                    int16_t _lo = (int16_t)(_i1 & 0xFFFF);                     \
                    uint32_t _iat_addr = _hi + _lo;                            \
                    uint32_t _iat_off = _iat_addr - PPC_IMAGE_BASE;            \
                    if (_iat_off + 4 <= PPC_IMAGE_SIZE) {                      \
                        uint32_t _real = __builtin_bswap32(                    \
                            *(uint32_t*)(base + _iat_off));                    \
                        auto _fn2 = PPC_LOOKUP_FUNC(_real);                    \
                        if (_fn2) { _fn2(ctx, base); break; }                  \
                    }                                                          \
                }                                                              \
            }                                                                  \
        }                                                                      \
        /* Fallback: unresolved */                                             \
        {                                                                      \
            static int _miss_count = 0;                                        \
            if (_miss_count++ < 50)                                            \
                printf("[WARN] Unresolved indirect call: 0x%08X "              \
                       "(LR=0x%08X)\n", _target, ctx.lr.u32);                 \
        }                                                                      \
    } while (0)
#endif

// Timebase override -- intercept __rdtsc() calls generated by XenonRecomp
// for PPC mftb instructions. Scale from host TSC (~3-4 GHz) to Xbox 360
// timebase (49.875 MHz). Ported from simpsonsarcade's timing fix.
#include <rex/chrono/clock.h>
inline uint64_t __ppc_query_timebase() {
    return rex::chrono::Clock::QueryGuestTickCount();
}
#define __rdtsc() __ppc_query_timebase()
